### ISSUE TITLE
Does it will work for Legion y730?

### ISSUE THREAD

**Issue by Yerkon** [RaulPetr/Lenovo-Y530-Fan-Fix#1]
The same problem with y730

**Comment by RaulPetr** [comment]
You should give it a try. 
Before running the service I would make sure the registers are the same. To do that, install NotebookFanControl, and run ec-probe commands in cmd:

1. ec-probe.exe read 0xfe - should give a reading proportional to fan speed
2. ec-probe.exe read 0x56 - should give a reading of temperature

**Comment by Yerkon** [comment]
@RaulPetr , Thank you for your answer:) 
Currently notebook was sold, not actual
