### ISSUE TITLE
Fans do not turn off when under 55, but continue running at speed 16.

### ISSUE THREAD

**Issue by falojazz** [RaulPetr/Lenovo-Y530-Fan-Fix#3]
I've seen others have the same problem, like one guy on this forum: https://forums.lenovo.com/t5/Gaming-Laptops/Legion-Y530-Fan-Control/m-p/4169991?page=37

Fans are not even turning of when reaching below 32 degrees, and it seems to be random when they stop.

Otherwise, it makes a positive difference in fan usage, and the fans aren't running full blast anymore.

**Comment by RaulPetr** [comment]
I also had that problem ocasionally.
I'm not sure exactly on what's happening, but it seems to lock the fans at the lowest speed (the one they have before turning off). Maybe the lock command is somehow issued before the command that sets them to 0.
Anyways, the thing I would do then is to manually run the fan-set-auto (which unlocks the speed control, giving them the opportunity to shut down). Then, the service should do it's job in locking them at that speed.

**Comment by falojazz** [comment]
Thanks! This solved my problem! 
No more 16 speed fans, yay
